<a href="https://colab.research.google.com/github/goudaChees/MLstudy/blob/master/0621.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [ ]:
import pandas as pd
from io import StringIO

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/code/02.notebook/2. data_preprocessing/train_AV3.csv')

In [ ]:
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.isnull()

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0      False   False    False       False      False          False   
1      False   False    False       False      False          False   
2      False   False    False       False      False          False   
3      False   False    False       False      False          False   
4      False   False    False       False      False          False   
..       ...     ...      ...         ...        ...            ...   
609    False   False    False       False      False          False   
610    False   False    False       False      False          False   
611    False   False    False       False      False          False   
612    False   False    False       False      False          False   
613    False   False    False       False      False          False   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0              False              False        True             False   
1              False              False       False             False   
2              False              False       False             False   
3              False              False       False             False   
4              False              False       False             False   
..               ...                ...         ...               ...   
609            False              False       False             False   
610            False              False       False             False   
611            False              False       False             False   
612            False              False       False             False   
613            False              False       False             False   

     Credit_History  Property_Area  Loan_Status  
0             False          False        False  
1             False          False        False  
2             False          False        False  
3             False          False        False  
4             False          False        False  
..              ...            ...          ...  
609           False          False        False  
610           False          False        False  
611           False          False        False  
612           False          False        False  
613           False          False        False  

[614 rows x 13 columns]

In [ ]:
df.isnull().sum(axis=0)

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
csv_data = '''
A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
9.0,10.0,11.0,
13.0,14.0,15.0,16.0
'''

In [ ]:
df1 = pd.read_csv(StringIO(csv_data))

In [ ]:
df1

A     B     C     D
0   1.0   2.0   3.0   4.0
1   5.0   6.0   NaN   8.0
2   9.0  10.0  11.0   NaN
3  13.0  14.0  15.0  16.0

In [ ]:
type(df1)

pandas.core.frame.DataFrame

In [ ]:
df.isnull()

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0      False   False    False       False      False          False   
1      False   False    False       False      False          False   
2      False   False    False       False      False          False   
3      False   False    False       False      False          False   
4      False   False    False       False      False          False   
..       ...     ...      ...         ...        ...            ...   
609    False   False    False       False      False          False   
610    False   False    False       False      False          False   
611    False   False    False       False      False          False   
612    False   False    False       False      False          False   
613    False   False    False       False      False          False   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0              False              False        True             False   
1              False              False       False             False   
2              False              False       False             False   
3              False              False       False             False   
4              False              False       False             False   
..               ...                ...         ...               ...   
609            False              False       False             False   
610            False              False       False             False   
611            False              False       False             False   
612            False              False       False             False   
613            False              False       False             False   

     Credit_History  Property_Area  Loan_Status  
0             False          False        False  
1             False          False        False  
2             False          False        False  
3             False          False        False  
4             False          False        False  
..              ...            ...          ...  
609           False          False        False  
610           False          False        False  
611           False          False        False  
612           False          False        False  
613           False          False        False  

[614 rows x 13 columns]

In [ ]:
df1.isnull()

A      B      C      D
0  False  False  False  False
1  False  False   True  False
2  False  False  False   True
3  False  False  False  False

In [ ]:
df1.isnull().sum(axis=0)

A    0
B    0
C    1
D    1
dtype: int64

In [ ]:
df1.isnull().sum(axis=1)

0    0
1    1
2    1
3    0
dtype: int64

In [ ]:
df1.dropna(axis=1)

A     B
0   1.0   2.0
1   5.0   6.0
2   9.0  10.0
3  13.0  14.0

In [ ]:
df1.dropna(how='all')

A     B     C     D
0   1.0   2.0   3.0   4.0
1   5.0   6.0   NaN   8.0
2   9.0  10.0  11.0   NaN
3  13.0  14.0  15.0  16.0

In [ ]:
df1.dropna(thresh=4)

A     B     C     D
0   1.0   2.0   3.0   4.0
3  13.0  14.0  15.0  16.0

In [ ]:
df1.dropna(subset=['C'])

A     B     C     D
0   1.0   2.0   3.0   4.0
2   9.0  10.0  11.0   NaN
3  13.0  14.0  15.0  16.0

In [ ]:
from sklearn.impute import SimpleImputer
import numpy as np
imr = SimpleImputer(missing_values = np.nan , strategy = 'mean')

In [ ]:
imr = imr.fit(df1.values)

In [ ]:
imputed_data = imr.transform(df1.values)

In [ ]:
imputed_data

array([[ 1.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  6.        ,  9.66666667,  8.        ],
       [ 9.        , 10.        , 11.        ,  9.33333333],
       [13.        , 14.        , 15.        , 16.        ]])

In [ ]:
imr2 = SimpleImputer(missing_values = np.nan , strategy = 'constant', fill_value = 100)
imputed_data2 = imr2.fit_transform(df1.values)

In [ ]:
imputed_data2

array([[  1.,   2.,   3.,   4.],
       [  5.,   6., 100.,   8.],
       [  9.,  10.,  11., 100.],
       [ 13.,  14.,  15.,  16.]])

In [ ]:
df = pd.DataFrame([    ['green', 'M', 10.1, 'class1'],
    ['red', 'L', 13.5, 'class2'],
    ['blue', 'XL', 15.3, 'class1']])

In [ ]:
df.columns = ['color','size','price','label']

In [ ]:
df


color size  price   label
0  green    M   10.1  class1
1    red    L   13.5  class2
2   blue   XL   15.3  class1

In [ ]:
size_mapping = {'XL':3, 'L':2, 'M':1}

In [ ]:
df['size'].map(size_mapping)

0    1
1    2
2    3
Name: size, dtype: int64

In [ ]:
df['size'] = df['size'].map(size_mapping)

In [ ]:
df

color  size  price   label
0  green     1   10.1  class1
1    red     2   13.5  class2
2   blue     3   15.3  class1

In [ ]:
inv_size_mapping = {v:k for k , v in size_mapping.items()}

In [ ]:
inv_size_mapping

{1: 'M', 2: 'L', 3: 'XL'}

In [ ]:
df['size'].map(inv_size_mapping)

0     M
1     L
2    XL
Name: size, dtype: object

In [ ]:
df

color  size  price   label
0  green     1   10.1  class1
1    red     2   13.5  class2
2   blue     3   15.3  class1

In [ ]:
unique_labels = np.unique(df['label'])
unique_labels

array(['class1', 'class2'], dtype=object)

In [ ]:
class_mapping = {label:idx for idx, label in enumerate(unique_labels)}
class_mapping

{'class1': 0, 'class2': 1}

In [ ]:
df['label'] = df['label'].map(class_mapping)


In [ ]:
df

color  size  price  label
0  green     1   10.1      0
1    red     2   13.5      1
2   blue     3   15.3      0

In [ ]:
inv_class_mapping = {label:idx for idx, label in class_mapping.items()}
inv_class_mapping

{0: 'class1', 1: 'class2'}

In [ ]:
df['label'].map(inv_class_mapping)

0    class1
1    class2
2    class1
Name: label, dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder
class_le = LabelEncoder()

In [ ]:
y = class_le.fit_transform(df['label'].values)
y

array([0, 1, 0])

In [ ]:
class_le.inverse_transform(y)

array([0, 1, 0])

In [ ]:
from sklearn.preprocessing import OneHotEncoder
df

color  size  price  label
0  green     1   10.1      0
1    red     2   13.5      1
2   blue     3   15.3      0

In [ ]:
X = df[['color','size','price']].values

In [ ]:
X

array([['green', 1, 10.1],
       ['red', 2, 13.5],
       ['blue', 3, 15.3]], dtype=object)

In [ ]:
color_le = LabelEncoder()


In [ ]:
X[:, 0] = color_le.fit_transform(X[:,0])
X

array([[1, 1, 10.1],
       [2, 2, 13.5],
       [0, 3, 15.3]], dtype=object)

In [ ]:
from sklearn.compose import ColumnTransformer
ohe = ColumnTransformer([( "color",OneHotEncoder(),[0])],remainder = 'passthrough')
ohe.fit_transform(X)

array([[0.0, 1.0, 0.0, 1, 10.1],
       [0.0, 0.0, 1.0, 2, 13.5],
       [1.0, 0.0, 0.0, 3, 15.3]], dtype=object)

In [ ]:
pd.get_dummies(df[['color','size','price']], drop_first=True)

size  price  color_green  color_red
0     1   10.1            1          0
1     2   13.5            0          1
2     3   15.3            0          0

In [ ]:
df_wine = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data' , header=None)

In [ ]:
df_wine

0      1     2     3     4    5     6     7     8     9      10    11  \
0     1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04   
1     1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
2     1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
3     1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
4     1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
..   ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
173   3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
174   3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
175   3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
176   3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
177   3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

       12    13  
0    3.92  1065  
1    3.40  1050  
2    3.17  1185  
3    3.45  1480  
4    2.93   735  
..    ...   ...  
173  1.74   740  
174  1.56   750  
175  1.56   835  
176  1.62   840  
177  1.60   560  

[178 rows x 14 columns]

In [ ]:
df_wine.columns = ['Class label', 'Alcohol', 'Malic acid', 'Ash', 'Alcalinity of ash', 'Magnesium', 'Total phenols', 'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins', 'Color intensity', 'Hue', 'OD280/OD315 of diluted wines', 'Proline']

In [ ]:
np.unique(df_wine['Class label'])

array([1, 2, 3])

In [ ]:
df_wine.head(20)

In [ ]:
df_wine.shape

(178, 14)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = df_wine.iloc[:,1:].values
y = df_wine.iloc[:,0].values

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=0, stratify=y)

In [ ]:
X_train.shape

(124, 13)

In [ ]:
X_test.shape

(54, 13)

In [ ]:
y_train.shape

(124,)

In [ ]:
y_test.shape

(54,)

In [ ]:
ex = np.array([0,1,2,3,4,5])

In [ ]:
(ex-ex.min())/(ex.max()-ex.min())

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
(ex-ex.mean())/ex.std()

array([-1.46385011, -0.87831007, -0.29277002,  0.29277002,  0.87831007,
        1.46385011])

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
data = [[-1, 2], 
        [-0.5, 6], 
        [0, 10], 
        [1, 18]]

In [ ]:
mms = MinMaxScaler()

In [ ]:
mms.fit_transform(data)

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])